[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "beespaces-api"
authors = [{name = "Bruno Leupi", email = "bruno@bee365.ch"}]
dynamic = ["version", "description"]
